name: Enviar Notificaci칩n

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar email con Mailgun
        run: |
          curl -s --user "api:${{ secrets.MAILGUN_API_KEY }}" \
               https://api.mailgun.net/v3/${{ secrets.MAILGUN_DOMAIN }}/messages \
               -F from="${{ secrets.MAILGUN_FROM }}" \
               -F to="${{ secrets.MAILGUN_TO }}" \
               -F subject="Notificaci칩n autom치tica" \
               -F text="Hola, esta es una notificaci칩n enviada desde GitHub Actions 游비"
